### ISSUE TITLE
代码提示的类型标注不准确/不完善

### ISSUE THREAD

**Issue by ghtz08** [tensorflower/ArcFace-python#1]
比如一些地方
```python
#多多人脸信息
class ASF_MultiFaceInfo(Structure):
    faceRect:list
    faceOrient:list
```
像这里，faceRect 的类型实际是 MRECT 的指针（也就是 MRECT 的数组），使用 list 来标注类型会带入一些本身没有的代码提示，还有一个问题是使用 [0] 得到的子项没有代码提示。建议使用 `Sequence` 来标注，可以得到相对准确的代码提示，比如对于 faceRect 可以标注为 Sequence[MRECT]。

**Comment by tensorflower** [comment]
已添加，感谢反馈
